apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-deployment   # Name of your deployment
  labels:
    app: selenium
spec:
  replicas: 1                 # Number of pods
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
        - name: selenium-container           # Container name
          image: northamerica-northeast2-docker.pkg.dev/onyx-segment-477302-c1/selenium-tests/selenium-tests:latest
          ports:
            - containerPort: 4444             # Selenium container port
