apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-job
spec:
  template:
    spec:
      containers:
        - name: selenium-container
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}:${TAG}
          imagePullPolicy: Always
      restartPolicy: Never
