apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-job
spec:
  template:
    spec:
      containers:
        - name: selenium-container
          image: ${IMAGE_URL}
          imagePullPolicy: Always
      restartPolicy: Never
